# works for now. in our code we need to later fix things when we want to run outside of localhost
# to run first time:
# docker compose up --build
#
# later:
# docker compose up
# if it says permission denied, run:
# sudo chown -R $USER:$USER backend/generated/

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - .env
    command: sh -c "rm -rf /app/generated && npx prisma generate && npx prisma migrate deploy && npx ts-node-dev src/server.ts"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules: